apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: opencv
  template:
    metadata:
      labels:
        app: opencv
    spec:
      containers:
      - name: opencv
        image: opencv
        imagePullPolicy: Always
        env: 
        - name: FLASK_ENV
          value: docker
        - name: SOURCE
          value: rtsp://admin:admin@192.168.123.90:554/cam/realmonitor
        - name: OPENCV_LOG_LEVEL
          value: v
        - name: OPENCV_VIDEOIO_DEBUG
          value: "1"
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "8"

      # imagePullSecrets:
      # - name: harbor-pullsecret
